

export const leadsArr = [{
    fullName: "Bruce Wayne", 
    whyMatched: ["Software for warehouses suggests that he's in B2B business", "Large LTV since it's an enterprise software", "His company, Conduit has only been in business for 5 months.", "They currently have only 2 employees, suggesting that they don't have enough capacity to focus on outreach"],
    emailPersonalization: "I gotta hand it to you - that foosball playing robot you created is out of this world! I'm in awe.",
    conduit: "Software for warehouses to automate schedules with trucks. every",
    aboutLead: "He is a cool guys",
    education: "Bsc. Computer Science",
    topSkills: ['Management', 'Computer literate'],
    languages: ['English', 'Tamil', 'Sinhala'],
    title: 'CEO',
    address: 'Emerville, California, United States',
    company: 'Microsoft',
    comment: "",
},
{
    fullName: "John Smith",
    whyMatched: ["His company is in the B2B space", "Has experience with enterprise software solutions"],
    emailPersonalization: "Your work on the latest software project is impressive! I would love to learn more about your approach.",
    conduit: "Software for automating warehouse operations",
    aboutLead: "John is a dedicated and talented software developer",
    education: "Bsc. Computer Science",
    topSkills: ['Problem solving', 'UI design'],
    languages: ['English', 'Spanish'],
    title: 'Senior Developer',
    address: 'San Francisco, California, United States',
    company: 'Google',
    comment: "",
},
{
    fullName: "Jane Doe",
    whyMatched: ["Experience with B2B software solutions", "Specializes in front-end development"],
    emailPersonalization: "I was blown away by your portfolio! Your attention to detail is truly remarkable.",
    conduit: "Software for automating warehouse operations",
    aboutLead: "Jane is a skilled front-end developer with a passion for creating engaging user experiences",
    education: "Bsc. Computer Science",
    topSkills: ['Front-end development', 'Design'],
    languages: ['English', 'French', 'German'],
    title: 'UI Designer',
    address: 'New York City, New York, United States',
    company: 'Linkedin',
    comment: '',
},
{
    fullName: "Michael Johnson",
    whyMatched: ["Expertise in B2B software development", "Experience working with enterprise clients"],
    emailPersonalization: "Your work on the latest project is impressive! I would love to discuss your approach to building scalable solutions.",
    conduit: "Software for automating warehouse operations",
    aboutLead: "Michael is an experienced software developer with a focus on creating scalable solutions",
    education: "Bsc. Computer Science",
    topSkills: ['Software architecture', 'Backend development'],
    languages: ['English'],
    title: 'Lead Developer',
    address: 'Austin, Texas, United States',
    company: 'Facebook',
    comment: '',
},
{
    fullName: "Samantha Lee",
    whyMatched: ["Experience working with B2B clients", "Specializes in front-end development"],
    emailPersonalization: "Your portfolio is fantastic! Your designs are both beautiful and functional.",
    conduit: "Software for automating warehouse operations",
    aboutLead: "Samantha is a talented front-end developer with a passion for creating intuitive user experiences",
    education: "Bsc. Computer Science",
    topSkills: ['Front-end development', 'UI design'],
    languages: ['English', 'Mandarin'],
    title: 'Front-end Developer',
    address: 'Seattle, Washington, United States',
    company: 'Stark Industries',
    comment: '',
}]
